// Copyright 2024 Eugen Berencian. All Rights Reserved.


#include "EdGraphSchema_ComboGraph.h"

#include "ComboGraph.h"
#include "ComboGraphEdge.h"
#include "EdNode_ComboGraphEdge.h"
#include "EdNode_ComboGraphNode.h"
#include "ToolMenu.h"
#include "AssetSchemaActions/AssetSchemaAction_ComboGraph_NewEdge.h"
#include "AssetSchemaActions/AssetSchemaAction_ComboGraph_NewNode.h"
#include "DrawingPolicy/ComboGraphConnectionDrawingPolicy.h"
#include "Framework/Commands/GenericCommands.h"
#include "Nodes/ComboGraphNode.h"

#define LOCTEXT_NAMESPACE "AssetSchema_ComboGraph"

void UEdGraphSchema_ComboGraph::CreateDefaultNodesForGraph(UEdGraph& Graph) const
{
	Super::CreateDefaultNodesForGraph(Graph);
}

void UEdGraphSchema_ComboGraph::GetGraphContextActions(FGraphContextMenuBuilder& ContextMenuBuilder) const
{
	UComboGraph* Graph = CastChecked<UComboGraph>(ContextMenuBuilder.CurrentGraph->GetOuter());

	if (!Graph->NodeType)
		return;

	const FText AddToolTip = LOCTEXT("NewComboGraphNodeTooltip", "Add combo node here :)");

	TSet<TSubclassOf<UComboGraphNode>> Visited;

	FText Desc = Graph->NodeType.GetDefaultObject()->ContextMenuName;

	if (Desc.IsEmpty())
	{
		FString Title = Graph->NodeType->GetName();
		Title.RemoveFromEnd("_C");
		Desc = FText::FromString(Title);
	}

	if (!Graph->NodeType->HasAnyClassFlags(CLASS_Abstract))
	{
		const TSharedPtr<FAssetSchemaAction_ComboGraph_NewNode> NewNodeAction(
			new FAssetSchemaAction_ComboGraph_NewNode(
				LOCTEXT("ComboGraphNodeAction", "Combo Graph Node"), Desc, AddToolTip, 0));
		NewNodeAction->NodeTemplate = NewObject<UEdNode_ComboGraphNode>(ContextMenuBuilder.OwnerOfTemporaries);
		NewNodeAction->NodeTemplate->ComboGraphNode = NewObject<UComboGraphNode>(
			NewNodeAction->NodeTemplate, Graph->NodeType);
		NewNodeAction->NodeTemplate->ComboGraphNode->Graph = Graph;
		ContextMenuBuilder.AddAction(NewNodeAction);

		Visited.Add(Graph->NodeType);
	}

	for (TObjectIterator<UClass> It; It; ++It)
	{
		if (It->IsChildOf(Graph->NodeType) && !It->HasAnyClassFlags(CLASS_Abstract) && !Visited.Contains(*It))
		{
			TSubclassOf<UComboGraphNode> NodeType = *It;

			//Remove REINST assets caused by recompiling blueprint
			//Remove SKEL assets which are SkeletonClass generated by BlueprintCompilationManager
			if (It->GetName().StartsWith("REINST") || It->GetName().StartsWith("SKEL"))
				continue;

			if (!Graph->GetClass()->IsChildOf(NodeType.GetDefaultObject()->CompatibleGraphType))
				continue;

			Desc = NodeType.GetDefaultObject()->ContextMenuName;

			if (Desc.IsEmpty())
			{
				FString Title = NodeType->GetName();
				Title.RemoveFromEnd("_C");
				Desc = FText::FromString(Title);
			}

			TSharedPtr<FAssetSchemaAction_ComboGraph_NewNode> Action(
				new FAssetSchemaAction_ComboGraph_NewNode(
					LOCTEXT("ComboGraphNodeAction", "Combo Graph Node"), Desc, AddToolTip, 0));
			Action->NodeTemplate = NewObject<UEdNode_ComboGraphNode>(ContextMenuBuilder.OwnerOfTemporaries);
			Action->NodeTemplate->ComboGraphNode = NewObject<UComboGraphNode>(Action->NodeTemplate, NodeType);
			Action->NodeTemplate->ComboGraphNode->Graph = Graph;
			ContextMenuBuilder.AddAction(Action);

			Visited.Add(NodeType);
		}
	}
}

void UEdGraphSchema_ComboGraph::GetContextMenuActions(UToolMenu* Menu, UGraphNodeContextMenuContext* Context) const
{
	if (Context->Node)
	{
		{
			FToolMenuSection& Section = Menu->AddSection("ComboGraphAssetGraphSchemaNodeActions",
			                                             LOCTEXT("ClassActionsMenuHeader", "Node Actions"));
			Section.AddMenuEntry(FGenericCommands::Get().Delete);
			Section.AddMenuEntry(FGenericCommands::Get().Rename);
		}
	}

	Super::GetContextMenuActions(Menu, Context);
}

const FPinConnectionResponse UEdGraphSchema_ComboGraph::CanCreateConnection(const UEdGraphPin* A,
                                                                            const UEdGraphPin* B) const
{
	if (A->GetOwningNode() == B->GetOwningNode())
	{
		return FPinConnectionResponse(CONNECT_RESPONSE_DISALLOW,
		                              LOCTEXT("PinErrorSameNode", "Can't connect node to itself"));
	}

	const UEdGraphPin* Out = A;
	const UEdGraphPin* In = B;

	const UEdNode_ComboGraphNode* EdNodeOut = Cast<UEdNode_ComboGraphNode>(Out->GetOwningNode());
	const UEdNode_ComboGraphNode* EdNodeIn = Cast<UEdNode_ComboGraphNode>(In->GetOwningNode());

	if (!EdNodeOut || !EdNodeIn)
	{
		return FPinConnectionResponse(CONNECT_RESPONSE_DISALLOW,
		                              LOCTEXT("PinError", "EdNode_ComboGraphNode is invalid"));
	}

	FText ErrorMessage;
	if (!EdNodeOut->ComboGraphNode->CanCreateConnectionTo(EdNodeIn->ComboGraphNode,
	                                                      EdNodeOut->GetOutputPin()->LinkedTo.Num(), ErrorMessage))
	{
		return FPinConnectionResponse(CONNECT_RESPONSE_DISALLOW, ErrorMessage);
	}

	if (!EdNodeIn->ComboGraphNode->CanCreateConnectionFrom(EdNodeOut->ComboGraphNode,
	                                                       EdNodeIn->GetInputPin()->LinkedTo.Num(), ErrorMessage))
	{
		return FPinConnectionResponse(CONNECT_RESPONSE_DISALLOW, ErrorMessage);
	}

	if (EdNodeOut->ComboGraphNode->GetGraph()->bEdgeEnabled)
	{
		return FPinConnectionResponse(CONNECT_RESPONSE_MAKE_WITH_CONVERSION_NODE,
		                              LOCTEXT("PinConnect", "Connect nodes with edge"));
	}

	return FPinConnectionResponse(CONNECT_RESPONSE_MAKE, LOCTEXT("PinConnect", "Connect nodes"));
}

bool UEdGraphSchema_ComboGraph::TryCreateConnection(UEdGraphPin* A, UEdGraphPin* B) const
{
	const UEdNode_ComboGraphNode* NodeA = Cast<UEdNode_ComboGraphNode>(A->GetOwningNode());
	const UEdNode_ComboGraphNode* NodeB = Cast<UEdNode_ComboGraphNode>(B->GetOwningNode());

	for (const UEdGraphPin* TestPin : NodeA->GetOutputPin()->LinkedTo)
	{
		UEdGraphNode* ChildNode = TestPin->GetOwningNode();
		if (UEdNode_ComboGraphEdge* EdNode_Edge = Cast<UEdNode_ComboGraphEdge>(ChildNode))
		{
			ChildNode = EdNode_Edge->GetEndNode();
		}

		if (ChildNode == NodeB)
			return false;
	}

	if (NodeA && NodeB)
	{
		return Super::TryCreateConnection(NodeA->GetOutputPin(), NodeB->GetInputPin());
	}

	return false;
}

bool UEdGraphSchema_ComboGraph::CreateAutomaticConversionNodeAndConnections(UEdGraphPin* A, UEdGraphPin* B) const
{
	UEdNode_ComboGraphNode* NodeA = Cast<UEdNode_ComboGraphNode>(A->GetOwningNode());
	UEdNode_ComboGraphNode* NodeB = Cast<UEdNode_ComboGraphNode>(B->GetOwningNode());

	if (!NodeA || !NodeA->GetOutputPin() || !NodeB || !NodeB->GetInputPin())
		return false;

	const UComboGraph* Graph = NodeA->ComboGraphNode->GetGraph();

	const FVector2D InitPos((NodeA->NodePosX + NodeB->NodePosX) / 2, (NodeA->NodePosY + NodeB->NodePosY) / 2);

	FAssetSchemaAction_ComboGraph_NewEdge Action;
	Action.NodeTemplate = NewObject<UEdNode_ComboGraphEdge>(NodeA->GetGraph());
	Action.NodeTemplate->SetEdge(NewObject<UComboGraphEdge>(Action.NodeTemplate, Graph->EdgeType));
	UEdNode_ComboGraphEdge* EdgeNode = Cast<UEdNode_ComboGraphEdge>(
		Action.PerformAction(NodeA->GetGraph(), nullptr, InitPos, false));

	EdgeNode->CreateConnections(NodeA, NodeB);

	return true;
}

TSharedPtr<FEdGraphSchemaAction> UEdGraphSchema_ComboGraph::GetCreateCommentAction() const
{
	return Super::GetCreateCommentAction();
}

void UEdGraphSchema_ComboGraph::GetBreakLinkToSubMenuActions(UToolMenu* Menu, UEdGraphPin* InGraphPin)
{
	TMap<FString, uint32> LinkTitleCount;

	FToolMenuSection& Section = Menu->FindOrAddSection("ComboGraphAssetGraphSchemaPinActions");

	for (TArray<UEdGraphPin*>::TConstIterator Links(InGraphPin->LinkedTo); Links; ++Links)
	{
		const UEdGraphPin* Pin = *Links;
		FString TitleString = Pin->GetOwningNode()->GetNodeTitle(ENodeTitleType::ListView).ToString();
		FText Title = FText::FromString(TitleString);
		if (Pin->PinName != TEXT(""))
		{
			TitleString = FString::Printf(TEXT("%s (%s)"), *TitleString, *Pin->PinName.ToString());

			FFormatNamedArguments Args;
			Args.Add(TEXT("NodeTitle"), Title);
			Args.Add(TEXT("PinName"), Pin->GetDisplayName());
			Title = FText::Format(LOCTEXT("BreakDescPin", "{NodeTitle} ({PinName})"), Args);
		}

		uint32& Count = LinkTitleCount.FindOrAdd(TitleString);

		FText Description;
		FFormatNamedArguments Args;
		Args.Add(TEXT("NodeTitle"), Title);
		Args.Add(TEXT("NumberOfNodes"), Count);

		if (Count == 0)
		{
			Description = FText::Format(LOCTEXT("BreakDesc", "Break link to {NodeTitle}"), Args);
		}
		else
		{
			Description = FText::Format(LOCTEXT("BreakDescMulti", "Break link to {NodeTitle} ({NumberOfNodes})"), Args);
		}
		++Count;

		Section.AddMenuEntry(NAME_None, Description, Description, FSlateIcon(), FUIAction(
			                     FExecuteAction::CreateUObject(this, &UEdGraphSchema_ComboGraph::BreakSinglePinLink,
			                                                   const_cast<UEdGraphPin*>(InGraphPin), *Links)));
	}
}

FConnectionDrawingPolicy* UEdGraphSchema_ComboGraph::CreateConnectionDrawingPolicy(int32 InBackLayerID,
	int32 InFrontLayerID, float InZoomFactor, const FSlateRect& InClippingRect, FSlateWindowElementList& InDrawElements,
	UEdGraph* InGraphObj) const
{
	return new FComboGraphConnectionDrawingPolicy(InBackLayerID, InFrontLayerID, InZoomFactor, InClippingRect,
	                                              InDrawElements, InGraphObj);
}

#undef LOCTEXT_NAMESPACE
